// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProfiledLink {
  /**
   * Innhold
   */
  contentUrl?: string;

  /**
   * Lenketekst
   */
  text?: string;

  /**
   * Med ikon
   */
  withIcon: boolean;
}
