// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface TablePartConfig {
  /**
   * Velg tabell
   */
  table?: string
}
