// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface RelatedFactPage {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Innholdsliste
   */
  itemList?: string;

  /**
   * Faktasider
   */
  relatedFactPages?: Array<string> | string;
}
