// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProfiledLinkIconPartConfig {
  /**
   * Lenker
   */
  profiledLinkItemSet?: Array<{
    /**
     * Lenketekst
     */
    text?: string

    /**
     * Innhold
     */
    href?: string
  }>
}
