// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface StandardCardsList {
  /**
   * Tittel
   */
  title?: string

  /**
   * Innhold
   */
  statisticsItemSet?: Array<{
    /**
     * Ikon
     */
    icon?: string

    /**
     * Innhold fra XP
     */
    contentXP?: string

    /**
     * Tittel
     */
    title?: string

    /**
     * Profileringstekst
     */
    profiledText?: string

    /**
     * Lenke
     */
    href?: string
  }>
}
