// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PubArchiveCalendarLinksPartConfig {
  /**
   * Lenke til Publikasjonsarkiv
   */
  pubArchiveUrl: string;

  /**
   * Lenke til Statistikk kalender
   */
  statCalendarUrl: string;
}
