# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: true

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - ssb-cgn
  # - Glenruben  I'll be back 😎
  - johnnadeluy
  - KyleDanny

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0

# A list of assignees, overrides reviewers if set
assignees:
  - ssb-cgn
  # - Glenruben  I'll be back 😎
  - johnnadeluy
  - KyleDanny

# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 1
# A list of keywords to be skipped the process that add reviewers if pull requests include it
# skipKeywords:
#   - wip

# filterLabels:
#   # Run
#   include:
#     - dependencies
