# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  # Grouping patch updates and minor updates into two pull requests for all packages
  groups:
    dependencies-patch-updates:
      update-types:
      - "patch"
    dependencies-minor-updates:
      update-types:
      - "minor"
  ignore:
  # enonic types should update only when updating enonic version on server
  - dependency-name: "@enonic-types/*"
- package-ecosystem: "gradle"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  commit-message: 
    prefix: "build"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  commit-message: 
    prefix: "build"
