---
kind: pipeline
type: docker
name: "Test Environment"
# Builds and tests on pull request. Required success before merge can happen.
trigger:
  branch:
    - master
  event:
    include:
      - pull_request
steps:
  - name: build & test
    image: enonic/enonic-ci:7.7-node
    commands:
      - /setup_sandbox.sh
      - enonic project build
  - name: deploy
    image: enonic/enonic-ci:7.7-node
    environment:
      ENONIC_CLI_REMOTE_URL:
        from_secret: ssb-xp7t-url
      ENONIC_CLI_REMOTE_USER:
        from_secret: ssb-xp7t-user
      ENONIC_CLI_REMOTE_PASS:
        from_secret: ssb-xp7t-pass
    commands:
      - enonic app install --file build/libs/*.jar
  - name: mabl create and test branch - test.ssb.no
    image: enonic/enonic-ci:7.7-node
    environment:
      MABL_API_KEY:
        from_secret: mabl-api-key
      MABL_APP_ID:
        from_secret: mabl-application-id
      MABL_ENV_ID_TEST:
        from_secret: mabl-env-test
    commands:
      - npm install -g @mablhq/mabl-cli 
      - mabl deployments create --api-key $MABL_API_KEY --application-id $MABL_APP_ID --labels MIMIR --environment-id $MABL_ENV_ID_TEST --revision $DRONE_COMMIT_SHA --await-completion --mabl-branch ${DRONE_SOURCE_BRANCH} --auto-branch true
---
kind: pipeline
type: docker
name: "QA Environment - promote"
# Deploy to qa on promoted builds
trigger:
  target:
    - qa
steps:
  - name: build & test
    image: enonic/enonic-ci:7.7-node
    commands:
      - /setup_sandbox.sh
      - enonic project build
  - name: deploy
    image: enonic/enonic-ci:7.7-node
    environment:
      ENONIC_CLI_REMOTE_URL:
        from_secret: ssb-xp7q-url
      ENONIC_CLI_REMOTE_USER:
        from_secret: ssb-xp7q-user
      ENONIC_CLI_REMOTE_PASS:
        from_secret: ssb-xp7q-pass
    commands:
      - enonic app install --file build/libs/*.jar
  - name: mabl end-to-end test
    image: enonic/enonic-ci:7.7-node
    environment:
      MABL_API_KEY:
        from_secret: mabl-api-key
      MABL_APP_ID:
        from_secret: mabl-application-id
      MABL_ENV_ID_QA:
        from_secret: mabl-env-qa
    commands:
      - npm install -g @mablhq/mabl-cli
      - mabl deployments create --api-key $MABL_API_KEY --application-id $MABL_APP_ID  --labels MIMIR --environment-id $MABL_ENV_ID_QA --await-completion
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_mimir_utv
      channel: mimir_utv
      template: >
        {{#success build.status}}
          🛠Build {{build.number}} deploy to QA succeeded. Good job.
        {{else}}
          💣Build {{build.number}} failed. {{build.author}} triggered the build. Maybe do a fix? Here's the failed build: {{build.link}}
        {{/success}}
    when:
      status: [success, failure]
---
kind: pipeline
type: docker
name: "QA Environment - Push to master"
# Deploy to qa on push to master
trigger:
  branch:
    - master
  event:
    include:
      - push
steps:
  - name: build & test
    image: enonic/enonic-ci:7.7-node
    commands:
      - /setup_sandbox.sh
      - enonic project build
  - name: deploy
    image: enonic/enonic-ci:7.7-node
    environment:
      ENONIC_CLI_REMOTE_URL:
        from_secret: ssb-xp7q-url
      ENONIC_CLI_REMOTE_USER:
        from_secret: ssb-xp7q-user
      ENONIC_CLI_REMOTE_PASS:
        from_secret: ssb-xp7q-pass
    commands:
      - enonic app install --file build/libs/*.jar
  - name: mabl end-to-end test
    image: enonic/enonic-ci:7.7-node
    environment:
      MABL_API_KEY:
        from_secret: mabl-api-key
      MABL_APP_ID:
        from_secret: mabl-application-id
      MABL_ENV_ID_QA:
        from_secret: mabl-env-qa
    commands:
      - npm install -g @mablhq/mabl-cli
      - mabl deployments create --api-key $MABL_API_KEY --application-id $MABL_APP_ID --environment-id $MABL_ENV_ID_QA --labels MIMIR --await-completion
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_mimir_utv
      channel: mimir_utv
      template: >
        {{#success build.status}}
          🛠Build {{build.number}} deploy to QA succeeded. Good job.
        {{else}}
          💣Build {{build.number}} failed. {{build.author}} triggered the build. Maybe do a fix? Here's the failed build: {{build.link}}
        {{/success}}
    when:
      status: [success, failure]
---
kind: pipeline
type: docker
name: "Production Environment"
# Deploy to prod on promoted builds
trigger:
  target:
    - prod
steps:
  - name: build & test
    image: enonic/enonic-ci:7.7-node
    commands:
      - /setup_sandbox.sh
      - enonic project build
  - name: deploy
    image: enonic/enonic-ci:7.7-node
    environment:
      ENONIC_CLI_REMOTE_URL:
        from_secret: ssb-xp7p-url
      ENONIC_CLI_REMOTE_USER:
        from_secret: ssb-xp7p-user
      ENONIC_CLI_REMOTE_PASS:
        from_secret: ssb-xp7p-pass
    commands:
      - enonic app install --file build/libs/*.jar
