apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: mimir-branch-{{branch}}
  namespace: ssbno
  annotations:
    nais.io/read-only-file-system: 'false'
    nais.io/run-as-user: '1337'
  labels:
    team: ssbno
spec:
  image: '{{ image }}'
  #  image: europe-north1-docker.pkg.dev/nais-management-b3a7/ssbno/ssbno-mimir/mimir:...
  #       ^--- interpolated from the ${{ env.docker_image }} variable in the action

  replicas:
    disableAutoScaling: true
    max: 1
    min: 1
  port: 8080

  # Server needs to be able to access these hosts to download and install apps from market, not a complete list, some apps can't be installed
  accessPolicy:
    outbound:
      external:
        - host: market.enonic.com
          ports:
            - port: 443
        - host: repo.enonic.com
          ports:
            - port: 443
        - host: github.com
          ports:
            - port: 22
            - port: 9418
        - host: raw.githubusercontent.com
          ports:
            - port: 22
            - port: 443
        - host: www.qa.ssb.no
          ports:
            - port: 443
        - host: i.qa.ssb.no
          ports:
            - port: 443
        - host: ext-i.qa.ssb.no
          ports:
            - port: 443
        - host: data.qa.ssb.no
          ports:
            - port: 443
        - host: statreg-rapport.staging.ssb.no
          ports:
            - port: 443
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 2Gi

  ttl: 168h

  prometheus:
    enabled: false

  envFrom:
    - secret: gitpull-config
  filesFrom:
    - secret: gitpull-key-private
      mountPath: /ssh

  env:
    - name: VHOST_HOST
      value: ssbno-{{branch}}.intern.test.ssb.no

  ingresses:
    - https://ssbno-{{branch}}.intern.test.ssb.no # must match vhost
