/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface Contact {
  /**
   * Navn på kontakt
   */
  name: string;

  /**
   * Epostadresse
   */
  email?: string;

  /**
   * Telefonnummer
   */
  phone?: string;

  /**
   * GraphQL name. Also used for separating unions in TypeScript
   */
  __typename?: 'mimir_Contact_Data';
}
