// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface NameSearchPartConfig {
  /**
   * Ingress
   */
  nameSearchDescription?: string;

  /**
   * Lenke tittel
   */
  aboutLinkTitle: string;

  /**
   * Lenkemål
   */
  aboutLinkTarget?: string;
}
