// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Links {
  /**
   * Velg lenketype
   */
  linkTypes: "tableLink" | "headerLink" | "profiledLink";

  /**
   * Tittel
   */
  title?: string;

  /**
   * Lenketekst
   */
  description?: string;

  /**
   * Url
   */
  url?: string;

  /**
   * Relatert innhold
   */
  relatedContent?: string;

  /**
   * Lenketekst
   */
  linkText?: string;

  /**
   * URL
   */
  headerLinkHref?: string;

  /**
   * Innhold
   */
  linkedContent?: string;

  /**
   * Lenketekst
   */
  text?: string;

  /**
   * Med ikon
   */
  withIcon: boolean;

  /**
   * URL
   */
  profiledLinkHref?: string;

  /**
   * Innhold
   */
  contentUrl?: string;
}
