// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ColumnsConfig {
  /**
   * Vis som grid
   */
  isGrid: boolean;

  /**
   * Kolonnestørrelse
   */
  size: "a" | "b" | "c";
}
