/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface RewriteVarnish {
  /**
   * Lenker
   */
  requests?: Array<{
    /**
     * Lenke XP
     */
    requestUrl: string;

    /**
     * Aktiver regel
     */
    enableRule: boolean;
  }>;

  /**
   * GraphQL name. Also used for separating unions in TypeScript
   */
  __typename?: "mimir_RewriteVarnish_Data";
}
