/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type RewriteVarnish = {
  /**
   * Lenker
   */
  requests?: Array<{
    /**
     * Lenke XP
     */
    requestUrl: string;

    /**
     * Aktiver regel
     */
    enableRule: boolean;
  }>;
}
