/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface Triple {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Skjul tittel
   */
  hideTitle: boolean;
}
