// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface UpcomingReleases {
  /**
   * Ingress
   */
  preface: string;

  /**
   * Antall dager pr "side"
   */
  numberOfDays: string;
}
