// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface StatisticAlert {
  /**
   * Tekst
   */
  message: string;

  /**
   * Velg hvilken statistikk det gjelder her.
   */
  statisticIds?: Array<string>;

  /**
   * Velg for å gjelde alle statistikker
   */
  selectAllStatistics: boolean;
}
