/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface NameSearch {
  /**
   * Ingress
   */
  nameSearchDescription?: string;

  /**
   * Lenke tittel
   */
  aboutLinkTitle: string;

  /**
   * Lenkemål
   */
  aboutLinkTarget?: string;

  /**
   * Bruk på Forside
   */
  frontPage: boolean;
}
