/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface BanVarnishPageCache {
  /**
   * ID of content to clear
   */
  pageId: string;
}
