/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type BanVarnishPageCache = {
  /**
   * ID of content to clear
   */
  pageIds: Array<string> | string;
}
