/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface Attachment {
  /**
   * Lenketekst innhold
   */
  label?: string;

  /**
   * Fil
   */
  file?: string;

  /**
   * GraphQL name. Also used for separating unions in TypeScript
   */
  __typename?: 'mimir_Attachment_Data';
}
