// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Article {
  /**
   * Stikktittel
   */
  introTitle?: string

  /**
   * Vis publiseringsdato
   */
  showPublishDate: boolean

  /**
   * Endringsdato
   */
  showModifiedDate?: {
    /**
     * Selected
     */
    _selected: Array<'dateOption'>

    /**
     * Skal det vises dato?
     */
    dateOption: {
      /**
       * Vis klokkeslett for publisering
       */
      showModifiedTime: boolean

      /**
       * Tidspunkt for endring
       */
      modifiedDate?: string
    }
  }

  /**
   * Forfattere
   */
  authorItemSet?: Array<{
    /**
     * Navn
     */
    name?: string

    /**
     * E-post
     */
    email?: string
  }>

  /**
   * Ingress
   */
  ingress?: string

  /**
   * Artikkeltekst
   */
  articleText?: string

  /**
   * Tilhørende statistikk
   */
  associatedStatistics?: Array<
    | {
        /**
         * Selected
         */
        _selected: 'XP'

        /**
         * Lenke til tilhørende statistikk (XP)
         */
        XP: {
          /**
           * Statistikk
           */
          content?: string
        }
      }
    | {
        /**
         * Selected
         */
        _selected: 'CMS'

        /**
         * Lenke til tilhørende statistikk (4.7.)
         */
        CMS: {
          /**
           * URL
           */
          href?: string

          /**
           * Tittel
           */
          title?: string
        }
      }
  >

  /**
   * Arkiv
   */
  articleArchive?: Array<string>

  relatedStatisticsOptions?: Array<
    | {
        /**
         * Selected
         */
        _selected: 'xp'

        /**
         * Statistikk fra XP
         */
        xp: {
          /**
           * Statistikk
           */
          contentId?: string
        }
      }
    | {
        /**
         * Selected
         */
        _selected: 'cms'

        /**
         * Statistikk fra 4.7
         */
        cms: {
          /**
           * Tittel
           */
          title: string

          /**
           * Profileringstekst
           */
          profiledText: string

          /**
           * URL
           */
          url: string
        }
      }
  >

  /**
   * Relaterte eksterne lenker
   */
  relatedExternalLinkItemSet?: Array<{
    /**
     * Lenketekst
     */
    urlText: string

    /**
     * URL
     */
    url: string
  }>

  /**
   * Relaterte artikler
   */
  relatedArticles?: Array<
    | {
        /**
         * Selected
         */
        _selected: 'article'

        /**
         * Artikkel
         */
        article: {
          /**
           * Artikkel fra XP
           */
          article: string
        }
      }
    | {
        /**
         * Selected
         */
        _selected: 'externalArticle'

        /**
         * Artikkel fra 4.7-CMS
         */
        externalArticle: {
          /**
           * URL
           */
          url: string

          /**
           * Tittel
           */
          title: string

          /**
           * Type
           */
          type?: string

          /**
           * Dato
           */
          date?: string

          /**
           * Ingress
           */
          preface: string

          /**
           * Bilde
           */
          image: string
        }
      }
  >

  /**
   * Faktasider
   */
  relatedFactPages?: Array<string>

  /**
   * Kontakter
   */
  contacts?: Array<string>

  /**
   * Innholdstype
   */
  articleType?: 'report' | 'note' | 'analysis' | 'economicTrends' | 'discussionPaper'

  /**
   * Løpenummer
   */
  serialNumber?: string

  /**
   * ISBN-nummer
   */
  isbnNumber?: string

  /**
   * Prioritert visning på forside
   */
  frontPagePriority: '0' | '1'

  /**
   * Delemner
   */
  subtopic?: Array<string>
}
