// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Article {
  /**
   * Stikktittel
   */
  introTitle?: string;

  /**
   * Vis publiseringsdato
   */
  showPublishDate: boolean;

  /**
   * Endringsdato
   */
  showModifiedDate?: {
    /**
     * Selected
     */
    _selected: Array<"dateOption">;
    
    /**
     * Skal det vises dato?
     */
    dateOption: {
      /**
       * Vis klokkeslett for publisering
       */
      showModifiedTime: boolean;

      /**
       * Tidspunkt for endring
       */
      modifiedDate?: string;
    };
  };

  /**
   * Forfattere
   */
  authorItemSet?: Array<{
    /**
     * Navn
     */
    name?: string;

    /**
     * E-post
     */
    email?: string;
  }>;

  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Artikkeltekst
   */
  articleText?: string;

  /**
   * Tilhørende statistikk
   */
  associatedStatistics?: Array<
    | {
        /**
         * Selected
         */
        _selected: "XP";

        /**
         * Lenke til tilhørende statistikk (XP)
         */
        XP: {
          /**
           * Statistikk
           */
          content?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "CMS";

        /**
         * Lenke til tilhørende statistikk (4.7.)
         */
        CMS: {
          /**
           * URL
           */
          href?: string;

          /**
           * Tittel
           */
          title?: string;
        };
      }
  >;

  /**
   * Arkiv
   */
  articleArchive?: Array<string>;

  /**
   * Innholdstype
   */
  articleType?: "report" | "note" | "analysis" | "economicTrends" | "discussionPaper";

  /**
   * Løpenummer
   */
  serialNumber?: string;

  /**
   * ISBN nummer
   */
  isbnNumber?: string;

  /**
   * Prioritert visning på forside
   */
  frontPagePriority: "0" | "1";
}
