// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface LinksPartConfig {
  /**
   * Lenke type
   */
  linkTypes?:
    | {
        /**
         * Selected
         */
        _selected: "tableLink";

        /**
         * Tabell lenke
         */
        tableLink: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "headerLink";

        /**
         * Uthevet lenke
         */
        headerLink: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "profiledLink";

        /**
         * Profilert lenke
         */
        profiledLink: Record<string, unknown>;
      };
}
