/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface Statistics {
  /**
   * Statistikk
   */
  statistic?: string;

  /**
   * Endringsdato
   */
  showModifiedDate?:
    | {
        /**
         * Selected
         */
        _selected: 'modifiedOption';

        /**
         * Endringsmelding
         */
        modifiedOption: {
          /**
           * Dato og tid
           */
          lastModified?: string;

          /**
           * Endringstekst
           */
          modifiedText?: string;
        };
      };

  /**
   * Tabell
   */
  mainTable?: string;

  /**
   * Vedleggstabell eller figur
   */
  attachmentTablesFigures?: Array<string> | string;

  /**
   * Fritekstfelt
   */
  freeTextAttachmentTablesFigures?: string;

  /**
   * Om Statistikken
   */
  aboutTheStatistics?: string;

  /**
   * Nøkkeltall
   */
  statisticsKeyFigure?: string;

  /**
   * Lenker til tabeller i statistikkbanken
   */
  statbankLinkItemSet?: Array<{
    /**
     * Lenketekst
     */
    urlText: string;

    /**
     * URL
     */
    url: string;
  }>;

  /**
   * Antall tabeller i statbank
   */
  linkNumber?: string;


  relatedStatisticsOptions?: Array<
    | {
        /**
         * Selected
         */
        _selected: 'xp';

        /**
         * Statistikk fra XP
         */
        xp: {
          /**
           * Statistikk
           */
          contentId?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: 'cms';

        /**
         * Statistikk fra 4.7
         */
        cms: {
          /**
           * Tittel
           */
          title: string;

          /**
           * Profileringstekst
           */
          profiledText: string;

          /**
           * URL
           */
          url: string;
        };
      }
  >;

  /**
   * Relaterte eksterne lenker
   */
  relatedExternalLinkItemSet?: Array<{
    /**
     * Lenketekst
     */
    urlText: string;

    /**
     * URL
     */
    url: string;
  }>;

  /**
   * Relaterte artikler
   */
  relatedArticles?: Array<
    | {
        /**
         * Selected
         */
        _selected: 'article';

        /**
         * Artikkel
         */
        article: {
          /**
           * Artikkel fra XP
           */
          article: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: 'externalArticle';

        /**
         * Artikkel fra 4.7-CMS
         */
        externalArticle: {
          /**
           * URL
           */
          url: string;

          /**
           * Tittel
           */
          title: string;

          /**
           * Type
           */
          type?: string;

          /**
           * Dato
           */
          date?: string;

          /**
           * Ingress
           */
          preface: string;

          /**
           * Bilde
           */
          image: string;
        };
      }
  >;

  /**
   * Faktasider
   */
  relatedFactPages?: Array<string> | string;

  /**
   * Kontakter
   */
  contacts?: Array<string> | string;

  /**
   * Stikkord
   */
  keywords?: string;

  /**
   * Delemner
   */
  subtopic?: Array<string> | string;

  /**
   * Skjul statistikk fra statbank emnetre
   */
  hideFromList: boolean;

  /**
   * GraphQL name. Also used for separating unions in TypeScript
   */
  __typename?: 'mimir_Statistics_Data';
}
