/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type MailChimpForm = {
  /**
   * Ingress
   */
  text?: string;

  /**
   * Mailchimp endepunkt eller mailmojo url
   */
  mailchimpEndpoint: string;

  /**
   * Mailchimp ID
   */
  mailchimpId?: string;
}
