// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface MailChimpForm {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Ingress
   */
  text?: string;

  /**
   * Mailchimp endepunkt
   */
  mailchimpEndpoint?: string;

  /**
   * Mailchimp ID
   */
  mailchimpId?: string;
}
