/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface Employee {
  /**
   * Er forsker
   */
  isResearcher: boolean;

  /**
   * Fornavn
   */
  name: string;

  /**
   * Etternavn
   */
  surname: string;

  /**
   * Stilling
   */
  position?: string;

  /**
   * E-post
   */
  email?: string;

  /**
   * Telefon
   */
  phone?: string;

  /**
   * Forskningsområde eller avdeling
   */
  area?: string;

  /**
   * Kort om
   */
  description?: string;

  /**
   * Pressebilder
   */
  profileImages?: Array<string> | string;

  /**
   * Ansatt id Cristin
   */
  cristinId?: string;

  /**
   * Min CV
   */
  myCV?: string;

  /**
   * Prosjekter
   */
  projects?: Array<string> | string;

  /**
   * GraphQL name. Also used for separating unions in TypeScript
   */
  __typename?: 'mimir_Employee_Data';
}
