/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type UpcomingRelease = {
  /**
   * Publisering
   */
  date: string;

  /**
   * Innholdstype
   */
  contentType: 'article' | 'report' | 'analysis' | 'table' | 'activity' | 'statistics';

  /**
   * Hovedemne
   */
  mainSubject: string;

  /**
   * Lenke
   */
  href?: string;
}
