// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface LocalSearchPartConfig {
  /**
   * Søke tittel
   */
  title: string

  /**
   * Tekst i søkefelt
   */
  searchPlaceholder: string

  /**
   * Søkbar mappe
   */
  searchFolder: string
}
