// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Employee {
  /**
   * Er forsker
   */
  isResearcher: boolean;

  /**
   * Stilling
   */
  position?: string;

  /**
   * Epostadresse
   */
  email?: string;

  /**
   * Telefonnummer
   */
  phone?: string;

  /**
   * Kort om meg
   */
  description?: string;

  /**
   * Ansatt id Cristin
   */
  cristinId?: string;
}
