// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Project {
  /**
   * Tittel
   */
  projectTitle: string

  /**
   * Prosjekt/modellansvarlig
   */
  manager?: string

  /**
   * Velg mellom prosjekt eller modell
   */
  projectType?: 'project' | 'model'

  /**
   * Periode
   */
  projectPeriod?: string

  /**
   * Finansør
   */
  financier?: string

  /**
   * Ingress
   */
  ingress?: string

  /**
   * Prosjekttekst
   */
  body?: string

  /**
   * Prosjektdeltakere
   */
  participants?: string

  /**
   * Samarbeidspartnere
   */
  collaborators?: string
}
