/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type Accordion = import("./accordion").Accordion;
export type ActiveStatistics = import("./activeStatistics").ActiveStatistics;
export type Article = import("./article").Article;
export type ArticleArchive = import("./articleArchive").ArticleArchive;
export type ArticleList = import("./articleList").ArticleList;
export type AttachmentTablesFigures = import("./attachmentTablesFigures").AttachmentTablesFigures;
export type Banner = import("./banner").Banner;
export type BkibolCalculator = import("./bkibolCalculator").BkibolCalculator;
export type Button = import("./button").Button;
export type CategoryLinks = import("./categoryLinks").CategoryLinks;
export type Contact = import("./contact").Contact;
export type ContactForm = import("./contactForm").ContactForm;
export type Divider = import("./divider").Divider;
export type DownloadLink = import("./downloadLink").DownloadLink;
export type Employee = import("./employee").Employee;
export type EmployeeList = import("./employeeList").EmployeeList;
export type EndedStatistics = import("./endedStatistics").EndedStatistics;
export type EntryLinks = import("./entryLinks").EntryLinks;
export type ExternalCard = import("./externalCard").ExternalCard;
export type FactBox = import("./factBox").FactBox;
export type FrontPageBanner = import("./frontPageBanner").FrontPageBanner;
export type FrontpageKeyfigures = import("./frontpageKeyfigures").FrontpageKeyfigures;
export type Highchart = import("./highchart").Highchart;
export type Highmap = import("./highmap").Highmap;
export type HusleieCalculator = import("./husleieCalculator").HusleieCalculator;
export type InfoGraphics = import("./infoGraphics").InfoGraphics;
export type KeyFigure = import("./keyFigure").KeyFigure;
export type KpiCalculator = import("./kpiCalculator").KpiCalculator;
export type Links = import("./links").Links;
export type LocalSearch = import("./localSearch").LocalSearch;
export type MailChimpForm = import("./mailChimpForm").MailChimpForm;
export type Map = import("./map").Map;
export type Maths = import("./maths").Maths;
export type MenuBox = import("./menuBox").MenuBox;
export type MenuDropdown = import("./menuDropdown").MenuDropdown;
export type NameSearch = import("./nameSearch").NameSearch;
export type OmStatistikken = import("./omStatistikken").OmStatistikken;
export type PictureCardLinks = import("./pictureCardLinks").PictureCardLinks;
export type PifCalculator = import("./pifCalculator").PifCalculator;
export type ProfiledBox = import("./profiledBox").ProfiledBox;
export type ProfiledLinkIcon = import("./profiledLinkIcon").ProfiledLinkIcon;
export type Project = import("./project").Project;
export type PubArchiveCalendarLinks = import("./pubArchiveCalendarLinks").PubArchiveCalendarLinks;
export type PublicationArchive = import("./publicationArchive").PublicationArchive;
export type RelatedArticles = import("./relatedArticles").RelatedArticles;
export type RelatedExternalLinks = import("./relatedExternalLinks").RelatedExternalLinks;
export type RelatedFactPage = import("./relatedFactPage").RelatedFactPage;
export type RelatedKostra = import("./relatedKostra").RelatedKostra;
export type RelatedStatistics = import("./relatedStatistics").RelatedStatistics;
export type ReleasedStatistics = import("./releasedStatistics").ReleasedStatistics;
export type SearchResult = import("./searchResult").SearchResult;
export type StandardCardsList = import("./standardCardsList").StandardCardsList;
export type StatbankBox = import("./statbankBox").StatbankBox;
export type StatbankFrame = import("./statbankFrame").StatbankFrame;
export type StatbankLinkList = import("./statbankLinkList").StatbankLinkList;
export type StatbankSubjectTree = import("./statbankSubjectTree").StatbankSubjectTree;
export type StaticVisualization = import("./staticVisualization").StaticVisualization;
export type Statistics = import("./statistics").Statistics;
export type SubjectArticleList = import("./subjectArticleList").SubjectArticleList;
export type Table = import("./table").Table;
export type UpcomingReleases = import("./upcomingReleases").UpcomingReleases;
export type Variables = import("./variables").Variables;

import { PartComponent } from '@enonic-types/core'
declare global {
  namespace XpPartComponent {
    export type Accordion = PartComponent<'mimir:accordion', XpPartMap['mimir:accordion']>
  }

  namespace XpComponent {
    export type Part = {
      [Property in keyof XpPartMap]: PartComponent<Property, XpPartMap[Property]>;
    }
  }

  interface XpPartMap {
    "mimir:accordion": Accordion;
    "mimir:activeStatistics": ActiveStatistics;
    "mimir:article": Article;
    "mimir:articleArchive": ArticleArchive;
    "mimir:articleList": ArticleList;
    "mimir:attachmentTablesFigures": AttachmentTablesFigures;
    "mimir:banner": Banner;
    "mimir:bkibolCalculator": BkibolCalculator;
    "mimir:button": Button;
    "mimir:categoryLinks": CategoryLinks;
    "mimir:contact": Contact;
    "mimir:contactForm": ContactForm;
    "mimir:divider": Divider;
    "mimir:downloadLink": DownloadLink;
    "mimir:employee": Employee;
    "mimir:employeeList": EmployeeList;
    "mimir:endedStatistics": EndedStatistics;
    "mimir:entryLinks": EntryLinks;
    "mimir:externalCard": ExternalCard;
    "mimir:factBox": FactBox;
    "mimir:frontPageBanner": FrontPageBanner;
    "mimir:frontpageKeyfigures": FrontpageKeyfigures;
    "mimir:highchart": Highchart;
    "mimir:highmap": Highmap;
    "mimir:husleieCalculator": HusleieCalculator;
    "mimir:infoGraphics": InfoGraphics;
    "mimir:keyFigure": KeyFigure;
    "mimir:kpiCalculator": KpiCalculator;
    "mimir:links": Links;
    "mimir:localSearch": LocalSearch;
    "mimir:mailChimpForm": MailChimpForm;
    "mimir:map": Map;
    "mimir:maths": Maths;
    "mimir:menuBox": MenuBox;
    "mimir:menuDropdown": MenuDropdown;
    "mimir:nameSearch": NameSearch;
    "mimir:omStatistikken": OmStatistikken;
    "mimir:pictureCardLinks": PictureCardLinks;
    "mimir:pifCalculator": PifCalculator;
    "mimir:profiledBox": ProfiledBox;
    "mimir:profiledLinkIcon": ProfiledLinkIcon;
    "mimir:project": Project;
    "mimir:pubArchiveCalendarLinks": PubArchiveCalendarLinks;
    "mimir:publicationArchive": PublicationArchive;
    "mimir:relatedArticles": RelatedArticles;
    "mimir:relatedExternalLinks": RelatedExternalLinks;
    "mimir:relatedFactPage": RelatedFactPage;
    "mimir:relatedKostra": RelatedKostra;
    "mimir:relatedStatistics": RelatedStatistics;
    "mimir:releasedStatistics": ReleasedStatistics;
    "mimir:searchResult": SearchResult;
    "mimir:standardCardsList": StandardCardsList;
    "mimir:statbankBox": StatbankBox;
    "mimir:statbankFrame": StatbankFrame;
    "mimir:statbankLinkList": StatbankLinkList;
    "mimir:statbankSubjectTree": StatbankSubjectTree;
    "mimir:staticVisualization": StaticVisualization;
    "mimir:statistics": Statistics;
    "mimir:subjectArticleList": SubjectArticleList;
    "mimir:table": Table;
    "mimir:upcomingReleases": UpcomingReleases;
    "mimir:variables": Variables;
  }
}
