// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface KpiCalculator {
  /**
   * Artikkel Kpi kalkulator
   */
  kpiCalculatorArticle?: string;

  /**
   * Bruk på Forside
   */
  frontPage: boolean;

  /**
   * Ingress kalkulator Forside
   */
  ingressFrontpage?: string;
}
