// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface MenuDropdownPartConfig {
  /**
   * Meny
   */
  menu: string;

  /**
   * Hovedside
   */
  basePage: string;

  /**
   * Kommunefakta versjon
   */
  modeMunicipality: boolean;
}
