// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ExternalCardPartConfig {
  /**
   * Ekstern card
   */
  externalCards: Array<{
    /**
     * Bilde
     */
    image: string

    /**
     * Tekst
     */
    content: string

    /**
     * Lenke tekst
     */
    linkText: string

    /**
     * Lenke url
     */
    linkUrl: string
  }>
}
