// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface HeaderLinkConfig {
  /**
   * Innhold
   */
  linkedContent: string;

  /**
   * Lenketekst
   */
  linkText: string;
}
