/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type RelatedKostra = {
  /**
   * Overskrft
   */
  title: string;

  /**
   * Beskrivelse
   */
  description: string;

  /**
   * KOSTRA lenke tekst
   */
  kostraLinkText: string;

  /**
   * KOSTRA lenke
   */
  kostraLink: string;
}
