/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type ArticleArchive = {
  /**
   * Ingress
   */
  preamble?: string;

  /**
   * Bilde
   */
  image?: string;

  /**
   * Fritekst
   */
  freeText?: string;

  /**
   * ISSN-nummer
   */
  issnNumber?: string;
}
