/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface ArticleArchive {
  /**
   * Ingress
   */
  preamble?: string;

  /**
   * Bilde
   */
  image?: string;

  /**
   * Fritekst
   */
  freeText?: string;

  /**
   * ISSN-nummer
   */
  issnNumber?: string;

  /**
   * GraphQL name. Also used for separating unions in TypeScript
   */
  __typename?: "mimir_ArticleArchive_Data";
}
