/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface BannerPartConfig {
  /**
   * Bakgrunnsbilde
   */
  image?: string;

  /**
   * Hvor skal banneret brukes?
   */
  pageType:
    | {
        /**
         * Selected
         */
        _selected: 'kommunefakta';

        /**
         * Kommunefakta
         */
        kommunefakta: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: 'faktaside';

        /**
         * Faktaside
         */
        faktaside: {
          /**
           * Stikktittel
           */
          subTitle?: string;

          /**
           * Tittel på faktaside
           */
          title?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: 'general';

        /**
         * Annet
         */
        general: {
          /**
           * Tittel
           */
          generalTitle?: string;
        };
      };
}
