/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type PubArchiveCalendarLinks = {
  /**
   * Lenke til Publikasjonsarkiv
   */
  pubArchiveUrl: string;

  /**
   * Lenke til Statistikk kalender
   */
  statCalendarUrl: string;
}
