// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface TableLinkConfig {
  /**
   * Tittel
   */
  title: string

  /**
   * Lenketekst
   */
  description: string

  /**
   * Url
   */
  href?: string

  /**
   * Relatert innhold
   */
  relatedContent?: string
}
