/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type CalculatorConfig = {
  /**
   * Kilde Årstall
   */
  kpiSourceYear?: string;

  /**
   * Kilde Måned
   */
  kpiSourceMonth?: string;

  /**
   * Kilde
   */
  pifSource?: string;

  /**
   * Kilde enebolig
   */
  bkibolSourceEnebolig?: string;

  /**
   * Kilde boligblokk
   */
  bkibolSourceBoligblokk?: string;

  /**
   * PX-API spørring for historiske navnedata
   */
  nameSearchGraphData?: string;
}
