/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface TableLink {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Lenketekst
   */
  description?: string;

  /**
   * Url
   */
  url?: string;

  /**
   * Relatert innhold
   */
  relatedContent?: string;
}
