// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Statistics {
  /**
   * Endringsdato
   */
  showModifiedDate?:
    | {
        /**
         * Selected
         */
        _selected: "modifiedOption";

        /**
         * Endringsmelding
         */
        modifiedOption: {
          /**
           * Dato og tid
           */
          lastModified?: string;

          /**
           * Endringstekst
           */
          modifiedText?: string;
        };
      };

  /**
   * Tabell
   */
  mainTable?: string;

  /**
   * Vedleggstabell eller figur
   */
  attachmentTablesFigures?: Array<string>;

  /**
   * Fritekstfelt
   */
  freeTextAttachmentTablesFigures?: string;

  /**
   * Om Statistikken
   */
  aboutTheStatistics?: string;

  /**
   * Nøkkeltall
   */
  statisticsKeyFigure?: string;

  /**
   * Lenker til tabeller i statistikkbanken
   */
  statbankLinkItemSet?: Array<{
    /**
     * Lenketekst
     */
    urlText: string;

    /**
     * URL
     */
    url: string;
  }>;

  /**
   * Antall tabeller i statbank
   */
  linkNumber?: string;

  /**
   * Stikkord
   */
  keywords?: string;

  /**
   * Skjul statistikk fra statbank emnetre
   */
  hideFromList: boolean;
}
