/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface ContentList {
  /**
   * innhold
   */
  contentList?: Array<string> | string;

  /**
   * GraphQL name. Also used for separating unions in TypeScript
   */
  __typename?: "mimir_ContentList_Data";
}
