/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type Accordion = import("./accordion").Accordion;
export type Article = import("./article").Article;
export type ArticleArchive = import("./articleArchive").ArticleArchive;
export type Attachment = import("./attachment").Attachment;
export type Button = import("./button").Button;
export type CalculatorConfig = import("./calculatorConfig").CalculatorConfig;
export type Contact = import("./contact").Contact;
export type ContentList = import("./contentList").ContentList;
export type Dashboard = import("./dashboard").Dashboard;
export type Employee = import("./employee").Employee;
export type EndedStatisticList = import("./endedStatisticList").EndedStatisticList;
export type FactBox = import("./factBox").FactBox;
export type Footer = import("./footer").Footer;
export type GenericDataImport = import("./genericDataImport").GenericDataImport;
export type Header = import("./header").Header;
export type Highchart = import("./highchart").Highchart;
export type Highmap = import("./highmap").Highmap;
export type InformationAlert = import("./informationAlert").InformationAlert;
export type KeyFigure = import("./keyFigure").KeyFigure;
export type Map = import("./map").Map;
export type MenuBox = import("./menuBox").MenuBox;
export type MenuDropdown = import("./menuDropdown").MenuDropdown;
export type MenuItem = import("./menuItem").MenuItem;
export type MunicipalityAlert = import("./municipalityAlert").MunicipalityAlert;
export type OmStatistikken = import("./omStatistikken").OmStatistikken;
export type OperationsAlert = import("./operationsAlert").OperationsAlert;
export type Page = import("./page").Page;
export type Project = import("./project").Project;
export type RewriteVarnish = import("./rewriteVarnish").RewriteVarnish;
export type StaticVisualization = import("./staticVisualization").StaticVisualization;
export type Statistics = import("./statistics").Statistics;
export type Table = import("./table").Table;
export type UpcomingRelease = import("./upcomingRelease").UpcomingRelease;

declare global {
  namespace XP {
    interface ContentTypes {
      "mimir:accordion": Accordion;
      "mimir:article": Article;
      "mimir:articleArchive": ArticleArchive;
      "mimir:attachment": Attachment;
      "mimir:button": Button;
      "mimir:calculatorConfig": CalculatorConfig;
      "mimir:contact": Contact;
      "mimir:contentList": ContentList;
      "mimir:dashboard": Dashboard;
      "mimir:employee": Employee;
      "mimir:endedStatisticList": EndedStatisticList;
      "mimir:factBox": FactBox;
      "mimir:footer": Footer;
      "mimir:genericDataImport": GenericDataImport;
      "mimir:header": Header;
      "mimir:highchart": Highchart;
      "mimir:highmap": Highmap;
      "mimir:informationAlert": InformationAlert;
      "mimir:keyFigure": KeyFigure;
      "mimir:map": Map;
      "mimir:menuBox": MenuBox;
      "mimir:menuDropdown": MenuDropdown;
      "mimir:menuItem": MenuItem;
      "mimir:municipalityAlert": MunicipalityAlert;
      "mimir:omStatistikken": OmStatistikken;
      "mimir:operationsAlert": OperationsAlert;
      "mimir:page": Page;
      "mimir:project": Project;
      "mimir:rewriteVarnish": RewriteVarnish;
      "mimir:staticVisualization": StaticVisualization;
      "mimir:statistics": Statistics;
      "mimir:table": Table;
      "mimir:upcomingRelease": UpcomingRelease;
    }
  }
}
