// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface HeaderLink {
  /**
   * Innhold
   */
  linkedContent?: string;

  /**
   * Lenketekst
   */
  linkText?: string;
}
