/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface SubjectTag {
  /**
   * Hovedemne eller Delemne
   */
  subjectType?: 'mainSubject' | 'subSubject';

  /**
   * Emnekode
   */
  subjectCode?: string;
}
