/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type EndedStatisticList = {
  /**
   * Statistikk
   */
  endedStatistics?: Array<{
    /**
     * Kortnavn
     */
    statistic: string;

    /**
     * Skjul statistikk fra statbank inngang
     */
    hideFromList: boolean;
  }>;
}
