// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PictureCardLinksPartConfig {
  /**
   * Redaksjonell boks
   */
  pictureCardLinks: Array<{
    /**
     * Tittel
     */
    title: string

    /**
     * Ingress
     */
    subTitle: string

    /**
     * Lenke
     */
    href: string

    /**
     * Bilde
     */
    image: string
  }>
}
