// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Map {
  /**
   * GraphQL name. Also used for separating unions in TypeScript
   */
  __typename?: "mimir_Map_Data";
}
