/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type ProfiledLink = {
  /**
   * Lenketekst
   */
  text?: string;

  /**
   * Med ikon
   */
  withIcon: boolean;

  /**
   * URL
   */
  profiledLinkHref?: string;

  /**
   * Innhold
   */
  contentUrl?: string;
}
