/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface EntryLinksPartConfig {
  /**
   * Inngang
   */
  entryLinks?: Array<{
    /**
     * Tittel
     */
    title: string;

    /**
     * URL
     */
    href: string;

    /**
     * Ikon
     */
    icon: string;

    /**
     * Mobil-Ikon
     */
    mobileIcon: string;
  }>;
}
