// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface RelatedArticles {
  /**
   * Relaterte artikler
   */
  relatedArticles?: Array<
    | {
        /**
         * Selected
         */
        _selected: 'article'

        /**
         * Artikkel
         */
        article: {
          /**
           * Artikkel fra XP
           */
          article: string
        }
      }
    | {
        /**
         * Selected
         */
        _selected: 'externalArticle'

        /**
         * Artikkel fra 4.7-CMS
         */
        externalArticle: {
          /**
           * URL
           */
          url: string

          /**
           * Tittel
           */
          title: string

          /**
           * Type
           */
          type?: string

          /**
           * Dato
           */
          date?: string

          /**
           * Ingress
           */
          preface: string

          /**
           * Bilde
           */
          image: string
        }
      }
  >
}
