// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface TopicConfig {
  /**
   * Tittel
   */
  title?: string

  /**
   * Skjul tittel
   */
  hideTitle: boolean
}
