// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ReleasedStatisticsPartConfig {
  /**
   * Antall statistikker i liste
   */
  numberOfStatistics: string;
}
