// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface InfoGraphicsPartConfig {
  /**
   * Tittel på visualinseringen
   */
  title: string;

  /**
   * Infografikk eller visualisering
   */
  image: string;

  /**
   * *IKKE LENGER I BRUK* (bruk alt tekst på valgt bilde)
   */
  altText?: string;

  /**
   * Beskrivende hjelpetekst for blinde
   */
  longDesc?: string;
}
