/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type Glossary = {
  /**
   * Ord
   */
  text: string;

  /**
   * Forklaring til ordet
   */
  explanation: string;
}
