// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FrontpageKeyfiguresPartConfig {
  /**
   * Nøkkeltall
   */
  keyfiguresFrontpage?: Array<{
    /**
     * Nøkkeltall
     */
    keyfigure?: string

    /**
     * Lenketekst
     */
    urlText: string

    /**
     * Lenke på nøkkeltall
     */
    url: string
  }>
}
