/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export type Columns = import("./columns").Columns;
export type Topic = import("./topic").Topic;
export type Triple = import("./triple").Triple;

declare global {
  interface XpLayoutMap {
    "mimir:columns": Columns;
    "mimir:topic": Topic;
    "mimir:triple": Triple;
  }
}
