/* eslint-disable prettier/prettier */ 
 // WARNING: This file was automatically generated by no.item.xp.codegen. You may lose your changes if you edit it.
export interface MenuBoxPartConfig {
  /**
   * Kort
   */
  menu: string;

  /**
   * Høyde på bokser
   */
  height: 'default' | 'fixed';
}
