// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Highmap {
  /**
   * Undertittel
   */
  subtitle?: string;

  /**
   * Forklaring datagrunnlag for skjermlesere
   */
  description?: string;

  /**
   * Kart fil (json format)
   */
  mapfile?: string;

  /**
   * Kartdata fra tabell (tabell limt inn fra excel)
   */
  htmlTable?: string;

  /**
   * Terskelverdi (1-5)
   */
  thresholdValue?: string;

  /**
   * Skjul navn i kart
   */
  hideName: boolean;

  /**
   * Velg fargepalett
   */
  colorPalette: "green" | "yellow";

  /**
   * Antall desimalplasser som vises
   */
  decimals?: string;

  /**
   * Høyde i prosent av bredde
   */
  heightPercent?: string;

  /**
   * Serietittel
   */
  seriesTitle?: string;

  /**
   * Tegnforklaring tittel
   */
  legendTitle?: string;

  /**
   * Plassering av tegnforklaring
   */
  legendPlacement: "topLeft" | "topRight" | "bottomLeft" | "bottomRight";

  /**
   * Fotnote-tekst
   */
  footnoteText?: string;
}
