name: "Deploy to QA"
on:
  push:
    branches:
      - "develop"
  workflow_dispatch: # Allows the workflow to be manually triggered.

concurrency:
  group: mimir-qa
  cancel-in-progress: true

jobs:
  deploy_to_qa:
    name: "Deploy to QA"
    permissions:
      contents: write
    runs-on: "ubuntu-latest"
    environment: "QA"
    steps:
      - uses: actions/checkout@v4
      - id: build_app
        uses: enonic/action-app-build@1ba16aae913a2637bfea0a1f8fcb51b3cb1afa2f # v2.0.0
      - name: Upload artifacts
        id: upload_artifacts
        if: success()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        env:
          RUN_NUMBER: ${{ github.run_number }}
        with:
          name: mimir-qa-$RUN_NUMBER
          path: "./build/libs/*.jar"
      - id: deploy_app_to_XP
        uses: "enonic/action-app-deploy@8ce05302b29df139a74241eaf59506b5043f8122" # v1.0.1
        with:
          url: ${{ secrets.ENONIC_QA_URL }}
          username: ${{ secrets.ENONIC_USER }}
          password: ${{ secrets.ENONIC_QA_PASS }}
          client_cert: ${{ secrets.ENONIC_DEPLOY_CERT }}
          client_key: ${{ secrets.ENONIC_DEPLOY_KEY }}
          app_jar: "./build/libs/*.jar"
      - name: Send failure message to Slack
        id: slack_failure
        if: steps.deploy_app_to_XP.outcome == 'failure'
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        env:
          ACTOR: ${{ github.actor }}
          REF: ${{ github.ref_name }}
          RUN_NUMBER: ${{ github.run_number }}
          WORKFLOW: ${{ github.workflow }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        with:
          webhook: ${{ secrets.SLACK_MIMIR_UTV }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                      "text": "${{ env.WORKFLOW }} in ${{ env.REPO }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                      "alt_text" : "Github logo"
                    },
                    {
                    "type": "mrkdwn",
                    "text": "Run by: *${{ env.ACTOR }}* on: *${{ env.REF }}*"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "💣 Build ${{ env.RUN_NUMBER }} is a *${{ job.status }}*, and that's cool!\nCommit message: *${{ env.COMMIT_MSG }}*\nIf you want to fix it, start by looking at the <https://github.com/${{ env.REPO }}/actions/runs/${{ env.RUN_ID }}|workflow output>"
                  }
                }
              ]
            }
  mabl_test:
    # Run this job after deploy is finished, and only run if deploy succeeded
    needs: deploy_to_qa
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - name: Git checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Branch name and commit hash
        run: |
          echo running on branch ${GITHUB_HEAD_REF##*/} or ${GITHUB_REF##*/}
          echo running $(echo $GITHUB_SHA | cut -c1-8) and ${GITHUB_SHA}
      - name: install mabl
        run: npm install -g @mablhq/mabl-cli
      - name: mabl end-to-end test - TEST
        run: mabl deployments create --api-key ${{ secrets.MABLAPIKEY }} --application-id ${{ secrets.MABLAPPID }} --environment-id ${{ secrets.MABLENVQA }} --labels MIMIR --await-completion
      - name: Send mabl test failure message to Slack
        if: failure()
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        env:
          ACTOR: ${{ github.actor }}
          REF: ${{ github.ref_name }}
          RUN_NUMBER: ${{ github.run_number }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        with:
          webhook: ${{ secrets.SLACK_MIMIR_MABL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                      "text": "Mabl Tests Failed in QA ${{ env.REPO }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                      "alt_text" : "Github logo"
                    },
                    {
                    "type": "mrkdwn",
                    "text": "Run by: *${{ env.ACTOR }}* on: *${{ env.REF }}*"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❌ Mabl tests failed for build ${{ env.RUN_NUMBER }}\nPlease check the <https://github.com/${{ env.REPO }}/actions/runs/${{ env.RUN_ID }}|workflow output> for details"
                  }
                }
              ]
            }
