
name: NAIS Deploy

on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "Deploy to Test"

jobs:
  nais-deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact URL & PR Info
        env:
          GITHUB_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
        run: |
          PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Previous Job ID: $PREVIOUS_JOB_ID"
          echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"

          ARTIFACT_URL=$(gh api "/repos/$OWNER/$REPO/actions/artifacts" \
            --jq ".artifacts.[] |
            select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
            select(.expired==false) |
            .archive_download_url")

          echo "ARTIFACT URL: $ARTIFACT_URL"
          echo "ARTIFACT_URL=$ARTIFACT_URL" >> "$GITHUB_ENV"
      # - uses: nais/deploy/actions/deploy@v1
      #   env:
      #     APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      #     CLUSTER: staging
      #     RESOURCE: nais.yaml
      #     VAR: image=todoTag,artifactUrl=${{ env.ARTIFACT_URL }}
      #     DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443