name: NAIS Deploy

on:
  pull_request:
    types: [labeled]

env:
  REGISTRY: europe-north1-docker.pkg.dev/nais-management-b3a7/ssbno/ssbno-mimir
  IMAGE: mimir
  TAG: ${{ github.head_ref }}-${{ github.sha }}

permissions:
  contents: read

jobs:
  build_xp:
    name: 'Build XP jar'
    runs-on: 'ubuntu-latest'
    if: (github.event.label.name == 'nais' && contains(fromJSON('["annesiri", "ssb-cgn", "Glenruben", "johnnadeluy", "Carl-OW"]'), github.actor))
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: build_app
        uses: 'enonic/action-app-build@846cdd20beec1404b7672baa8d85ee2ea228b380' # v1.0.0
      - name: Upload artifacts
        id: upload_artifacts
        if: success()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        env:
          RUN_NUMBER: ${{ github.run_number }}
        with:
          name: mimir-nais-$RUN_NUMBER
          path: './build/libs/*.jar'

  build_image_and_push:
    needs: build_xp
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Calculate sha
        id: calculate_sha
        run: echo ${{ env.REGISTRY }} && echo ${{ env.IMAGE }} && echo ${{ env.TAG }}

      - name: Checkout mimir
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Give GitHub Actions acces to docker repo
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.DOCKER_REPO_READ_KEY }}
      - name: Checkout docker
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: 'main'
          path: 'ssbno-xp-docker'
          repository: 'statisticsnorway/ssbno-xp-docker'
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        env:
          RUN_NUMBER: ${{ github.run_number }}
        with:
          name: mimir-nais-$RUN_NUMBER
          path: './ssbno-xp-docker'

      # turn 'MIM-9876_new_feature' into 'mim-9876' so it can be used in URL, it can be found in env.ISSUE_NUMBER
      - name: 'Get JIRA issue number'
        id: jira_issue_number
        env:
          BRANCH: ${{ github.head_ref }}
        run: |
          ISSUE_NUMBER=${BRANCH:0:8}
          ISSUE_NUMBER=$(echo $ISSUE_NUMBER | tr '[:upper:]' '[:lower:]')
          echo "ISSUE_NUMBER=${ISSUE_NUMBER}" >> $GITHUB_ENV;
          echo "Issue number: $ISSUE_NUMBER";

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
        with:
          workload_identity_provider: 'projects/906675412832/locations/global/workloadIdentityPools/ssb-identity-pool/providers/github-oidc-provider'
          service_account: 'gh-ssb@nais-management-b3a7.iam.gserviceaccount.com'
          token_format: 'access_token'
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: Login to registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      - name: Docker meta
        id: metadata
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha
            type=raw,value=${{ env.TAG }}, enable=true
      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        env:
          BRANCH: ${{ github.head_ref }}
        with:
          context: ./ssbno-xp-docker
          file: './ssbno-xp-docker/Dockerfile'
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          build-args: |
            BRANCH_NAME=$BRANCH
          labels: ${{ steps.metadata.outputs.labels }}

  deploy:
    name: Deploy to NAIS
    needs: build_image_and_push
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: 'Get JIRA issue number'
        id: jira_issue_number
        env:
          BRANCH: '${{ github.head_ref }}'
        run: |
          ISSUE_NUMBER=${BRANCH:0:8}
          ISSUE_NUMBER=$(echo $ISSUE_NUMBER | tr '[:upper:]' '[:lower:]')
          echo "ISSUE_NUMBER=${ISSUE_NUMBER}" >> $GITHUB_ENV;
          echo "Issue number: $ISSUE_NUMBER";
      - name: 'Store image tag'
        run: echo "IMAGE_TAG=${{ env.TAG }}" >> $GITHUB_ENV
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: test
          RESOURCE: nais.yaml
          VAR: image=${{ env.REGISTRY }}/${{env.IMAGE}}:${{ env.TAG }},branch=${{ env.ISSUE_NUMBER }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
      - name: Add comment to PR
        uses: the-wright-jamie/update-pr-info-action@3372c9a8262df9b267774d11accd1a4b5da1e2fd # v1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          head-branch-regex: 'mim-\d{2,4}'
          body-template: |
            ### Branch Deployment to NAIS!
            [🗄️ Link to branch admin interface!](https://ssbno-${{ env.ISSUE_NUMBER }}.intern.test.ssb.no/admin)
            [📰 Front page can be found here!](https://ssbno-${{ env.ISSUE_NUMBER }}.intern.test.ssb.no/)
          body-update-action: 'suffix'
