name: Release Please

on:
  workflow_dispatch:  # Only manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: ./release-please-config.json
          manifest-file: ./release-please-config.json
          release-type: java
          package-name: mimir
          target-branch: master
          default-branch: develop
          # Don't create releases, only handle version bumps
          release-labels: ""
          # Don't create tags
          include-component-in-tag: false
          # Don't create GitHub releases
          include-v-in-tag: false
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]' 